### ISSUE TITLE
sensitive information in ec2autorun.log

### ISSUE THREAD

**Issue by kaktus42** [galaxyproject/cloudman#16]
Cloudman logs access key, secret key and admin password in logfile.

prefixes with `Composed user data:`

**Comment by kaktus42** [comment]
comes from here: https://github.com/galaxyproject/ansible-cloudman-image/blob/master/files/ec2autorun.py#L573

**Comment by afgane** [comment]
Fixed in https://github.com/galaxyproject/ansible-cloudman-image/commit/dc95eb110b43f19183350abf0fbf347a032f94e6
