### ISSUE TITLE
Compatibility with CentOS/Fedora family systems [Enhancement]

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudman#24]
@afgane mentioned that Cloudman uses some commands specific to Ubuntu or Debian family systems and to [search for misc.run in the Cloudman repo](https://github.com/galaxyproject/cloudman/search?utf8=%E2%9C%93&q=misc.run). There is one hard-coded command that I do not find on my CentOS machine: [start-stop-daemon](https://github.com/galaxyproject/cloudman/blob/0c3728a38ecf9277757116d7e0617247fb9296e3/cm/services/apps/jobmanagers/slurmd.py) associated with the slurmd job manager. Otherwise, some of the commands executed are elements of iterable objects and are run in turn. I'm not sure what commands could be executed through this mechanism. Can someone point me in the right direction as to what commands are Ubuntu/Debian specific and then I can see if I can find an equivalent system command in CentOS?

**Comment by afgane** [comment]
There are a couple of apt-get commands I believe, but those are optional with the latest image so shouldn't be a problem. I'd say the best thing here is to just run and see if (or where) it fails. Besides looking for commands executed via `misc.run`, it'd be a pretty slow process to isolate any additional spots where a command might be called. 

As you start launching instances, take a look at the boot sequence log files to see how things are progressing: https://wiki.galaxyproject.org/CloudMan/Troubleshooting#Log_files

**Comment by MatthewRalston** [comment]
@afgane @dannon I'm closing this issue.
