### ISSUE TITLE
Transient nfs files are not shared

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudman#35]
Hi everyone,
I've got a cluster running where the directory /transient_nfs should be the ephemeral storage that is used by Cloudman to share the hosts and slurm.conf files. I've noticed that when I touch a file on either the client or server side, the file is not accessible across NFS. Strangely, the files that Cloudman created with the file lock are available.

**Comment by afgane** [comment]
I can't reproduce this - that scenario works fine when I try it:
![screen shot 2015-12-01 at 2 50 57 pm](https://cloud.githubusercontent.com/assets/338642/11512227/14e30a66-983b-11e5-8c0d-fe50a9770d0f.png)

Unless it's a typo, the only thing that I see is that you mention `/transient_nfs` - it's should be `/mnt/transient_nfs`?

**Comment by MatthewRalston** [comment]
Thanks @afgane I am not sure why I have that directory. I will close this.
