### ISSUE TITLE
Adjusting autoscaling parameters

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudman#37]
Hi everyone,
I am finding that Cloudman's autoscaling feature to be too conservative. I have a situation where I don't mind the extra cost of firing up new nodes and I simply want to clear the queue as quickly as possible. How can I adjust Cloudman to fire up new instances whenever it sees stalled jobs in the queue? Can someone shed light on to the formula or algorithm that Cloudman uses to decide when to launch a new node?

**Comment by afgane** [comment]
The autoscaling process is implemented in this file: https://github.com/galaxyproject/cloudman/blob/master/cm/services/autoscale.py

More specific to your question, you could set a shorter threshold time for jobs in the queue: https://github.com/galaxyproject/cloudman/blob/master/cm/services/autoscale.py#L104
or add more than one node at a time https://github.com/galaxyproject/cloudman/blob/master/cm/services/autoscale.py#L172

If you’re wanting to add nodes before previous one has been fully integrated into the cluster and started accepting jobs, you should remove the this line/condition: https://github.com/galaxyproject/cloudman/blob/master/cm/services/autoscale.py#L98

Autoscaling will get revamped one of these days to make it more configurable so I'll keep this in mind to push it higher up on the todo list.

**Comment by hackdna** [comment]
It would be great to be able to fine tune the autoscaling params from the admin console.

**Comment by afgane** [comment]
There are basically three variables at play here: 

1. mean time of running jobs (set at 60 seconds)
2. number of jobs queued (set to 2)
3. number of nodes to add (set to 1)

If the mean job runtime is greater then the set threshold (i.e., 60sec) and the number of queued jobs is greater then the threshold (i.e., 2), add the specified number of nodes (i.e., 1).

Would being able to set those parameters when turning on autoscaling solve the issues you guys are seeing?

**Comment by hackdna** [comment]
Yes. From highest to lowest importance: number of jobs queued, mean job run time threshold, number of nodes to add.

**Comment by afgane** [comment]
I made some changes to expose the three parameters in the UI. When turning on, or adjusting, autoscaling settings, you'll now also see Advanced options where you can change relevant values:
![screen shot 2016-03-01 at 4 11 11 pm](https://cloud.githubusercontent.com/assets/338642/13442010/468ace9e-dfc8-11e5-9650-ca52034cb0e2.png)

See how that does and we can always adjust. 
I've uploaded this code to _cloudman-test_ bucket.

**Comment by hackdna** [comment]
I've tested with min jobs = 1 and mean runtime = 1, and worker nodes were launched as soon as jobs were submitted (as expected). Thank you!

**Comment by afgane** [comment]
Glad to hear it. 

I'll close this issue for now then and we can always reopen if something different comes up.
