### ISSUE TITLE
Set master to not run jobs when autoscaling is enabled

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#40]
We have the following use case: run a small master node continuously (for web UI) and spin up workers on demand (with min: 0 and max: N).

Right now (using `cloudman-dev` bucket) when I enable autoscaling, the master is still set to run jobs. Also, even if I set the master not to run jobs, when the last idle worker terminates the master is set to run jobs again automatically:
```
22:58:21 - Initiated requested termination of instance. Terminating 'i-0e0226d1db2ed616b'.
22:58:21 - Initiated requested termination of instances. Terminating '1' instances.
22:58:21 - Terminating instance i-0e0226d1db2ed616b
22:58:24 - Instance 'i-0e0226d1db2ed616b' removed from the internal instance list.
22:58:24 - The master instance is set to execute jobs. To manually change this, use the CloudMan Admin panel.
```
It would be great to prevent the master from running jobs by default when autoscaling is enabled.

**Comment by afgane** [comment]
Master won't automatically switch to being an exec host as long as autoscaling is on now. I've uploaded this code to _cloudman-dev_ and _cloudman-test_ buckets.

**Comment by hackdna** [comment]
Thank you for a quick fix, I've tested this successfully using `cloudman-dev`. Looking forward to the next production release.
