### ISSUE TITLE
Cloning cluster fails due to missing permissions

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#41]
Target AWS account must have the `List` permission on the source S3 bucket. Also, target AWS account must have permission to access the _galaxyIndicesFS_ snapshot.

Neither permission is set by the automated sharing process (unlike the `Open/Download` permission on the source bucket objects). This results in failure to start the cluster and errors ('snap-7b992575' is the _galaxyIndicesFS_ snapshot):
```
22:10:01 - Shared cluster's bucket 'cm-5b88aa0dbe0f7fc5765ccdc7dc116101' does not exist or is not accessible!
22:20:10 - Created a data volume 'vol-30e69299' of size 200GB from shared cluster's snapshot 'snap-497a6b49'
22:20:11 - EC2ResponseError retrieving snapshot IDs ['snap-7b992575']: EC2ResponseError: 400 Bad Request InvalidSnapshot.NotFoundThe snapshot 'snap-7b992575' does not exist.81ea690c-4ff9-4171-8029-7572a36816f3
22:20:11 - Did not retrieve Snapshot object for snap-7b992575; aborting.
```

**Comment by afgane** [comment]
Above two commits should fix the issues you've encountered. There's now a new UI issue in that a clones cluster reports a message saying it's ready to go right after it starts up and before it's actually ready. It's confusing but not functionally problematic. I'll hopefully look at that later in the week. 

This code is is _cloudman-test_ bucket if you'd like to start using it.

**Comment by hackdna** [comment]
Thank you! I ended up cloning the cluster manually but looking forward to testing this when you've had a chance to address the UI issue.

**Comment by afgane** [comment]
Should be all ok now. Let me know if you find it not to be the case.
(code is _cloudman-test_ bucket)

**Comment by hackdna** [comment]
Thank you, this appears to work as expected now.
