### ISSUE TITLE
Change root volume type from magnetic (standard) to SSD (gp2)

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#43]
Recommended by Amazon: https://aws.amazon.com/ebs/details/

**Comment by afgane** [comment]
This requires a new image, which I just built and linked to the launcher if you're like to give it a go:
![screen shot 2016-03-11 at 3 19 05 pm](https://cloud.githubusercontent.com/assets/338642/13714539/28819400-e79d-11e5-878f-f44266072992.png)

Thanks for all the performance improvement suggestions btw.

**Comment by hackdna** [comment]
No worries, thank you for fixing all these issues so quickly! Node boot time is a lot shorter now.
