### ISSUE TITLE
Specifying memory requirements for jobs doesn't have effect

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#45]
I'm running a single worker node with 32GB of memory to run jobs that can require 20-25GB of memory each (`slurm.conf`):
```
# COMPUTE NODES
NodeName=master NodeAddr=127.0.0.1 CPUs=1 RealMemory=3764 Weight=10 State=UNKNOWN
NodeName=w3 NodeAddr=172.31.18.72 CPUs=16 RealMemory=30148 Weight=5 State=UNKNOWN
```
I'm using `--mem 25000` as a destination parameter for these jobs (`job_conf.xml`):
```
        <destination id="slurm_memory" runner="slurm">
            <param id="nativeSpecification">--mem=25000</param>
        </destination>
...
<tool id="wig_to_bigWig" destination="slurm_memory"/>
```
```
galaxy.jobs.runners DEBUG 2016-03-21 21:34:33,707 (1059) command is: grep -v "^track" /mnt/galaxy/files/001/dataset_1381.dat | wigToBigWig stdin /mnt/galaxy/galaxy-app/tool-data/len/hg19.len /mnt/galaxy/files/001/dataset_1382.dat -clip 2>&1 || echo "Error running wigToBigWig." >&2; return_code=$?; python "/mnt/galaxy/tmp/job_working_directory/001/1059/set_metadata_oOH2bq.py" "/mnt/galaxy/tmp/tmpC8piC7" "/mnt/galaxy/tmp/job_working_directory/001/1059/galaxy.json" "/mnt/galaxy/tmp/job_working_directory/001/1059/metadata_in_HistoryDatasetAssociation_1436_b78YRM,/mnt/galaxy/tmp/job_working_directory/001/1059/metadata_kwds_HistoryDatasetAssociation_1436_FTWZDJ,/mnt/galaxy/tmp/job_working_directory/001/1059/metadata_out_HistoryDatasetAssociation_1436_PdF3Qh,/mnt/galaxy/tmp/job_working_directory/001/1059/metadata_results_HistoryDatasetAssociation_1436_bflH3p,/mnt/galaxy/files/001/dataset_1382.dat,/mnt/galaxy/tmp/job_working_directory/001/1059/metadata_override_HistoryDatasetAssociation_1436_1t3RXZ" 5242880; sh -c "exit $return_code"
galaxy.jobs.runners.drmaa DEBUG 2016-03-21 21:34:33,913 (1059) submitting file /mnt/galaxy/tmp/job_working_directory/001/1059/galaxy_1059.sh
galaxy.jobs.runners.drmaa DEBUG 2016-03-21 21:34:33,913 (1059) native specification is: --mem=25000
galaxy.jobs.runners.drmaa INFO 2016-03-21 21:34:33,917 (1059) queued as 10
galaxy.jobs DEBUG 2016-03-21 21:34:33,965 (1059) Persisting job destination (destination id: slurm_memory)
galaxy.jobs.runners.drmaa DEBUG 2016-03-21 21:34:34,134 (1059/10) state change: job is running
```
However, more than one job is allowed to run at a time which causes the node to run out of memory and jobs to be killed.

**Comment by afgane** [comment]
@natefoo, would you have some ideas/suggestions why this might be the case?

**Comment by natefoo** [comment]
@afgane can you point me at Cloudman's slurm.conf template?

@hackdna If you're using a relatively stock slurm.conf, it will use the linear scheduling plugin. To control memory/core usage you need to enable the consumable resources plugin: http://slurm.schedmd.com/cons_res.html

**Comment by afgane** [comment]
@natefoo Here it is: https://github.com/galaxyproject/cloudman/blob/master/cm/conftemplates/slurm.conf.default
As nodes get added, the file is edited to add node info under the _COPMUTE NODES_ 'section': https://github.com/galaxyproject/cloudman/blob/master/cm/services/apps/jobmanagers/slurmctld.py#L115

**Comment by hackdna** [comment]
I'm using unmodified CM `slurm.conf` which contains:
```
SchedulerType=sched/backfill
SelectType=select/cons_res
```
I've tried adding `SelectTypeParameters=CR_Core_Memory` as the Slurm docs suggested but `slurm.conf` keeps getting reverted for some reason after slurmctld is restarted.

**Comment by afgane** [comment]
Can you try restarting slurmctld via the command line vs. using CloudMan? CloudMan rewrites Slurm's conf when the service is restarted (the refactored CloudMan will support user configuration changes but that's months away). The command CloudMan is using should be in its log file.

**Comment by hackdna** [comment]
Thanks, that worked. Would you mind adding `SelectTypeParameters=CR_Core_Memory` to `slurm.conf` as a default?
Speaking of restarting services via command line, what is the right way to do that for Galaxy in CM?

**Comment by afgane** [comment]
Done in a64eb57821a22e39a738271fb193254688623614.

For Galaxy, take a look at this page, I just added the exact command: https://wiki.galaxyproject.org/CloudMan/Services/Galaxy

**Comment by hackdna** [comment]
Thank you @afgane and @natefoo.

**Comment by afgane** [comment]
No problem. Forgot to mention but the new code is in _cloudman-test_ bucket.
