### ISSUE TITLE
20 node limit???

### ISSUE THREAD

**Issue by MatthewRalston** [galaxyproject/cloudman#46]
Why is there a limit for the number of nodes

**Comment by afgane** [comment]
For a long time, that been the default AWS limit for number of instances one can launch and we just stuck with it. Also, the interface does not scale beyond 20 (although things will continue to work). I'll remove that limit in a bit.

**Comment by afgane** [comment]
Is this with enabling autoscaling? It don't see where the limit is actually enforced anywhere else, but as I said, the interface related to the instance display will not work as expected.
