### ISSUE TITLE
Galaxy FS usage and size displayed incorrectly for cloned clusters

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#50]
### Steps to reproduce
Clone a shared cluster with Galaxy FS volume with size of 200GB

### Observed results
CloudMan Console shows:
`Disk status: 5.7G / 20G (31%)`
CloudMan Admin Console shows under File systems (correctly):
`galaxy 26 GB/199.9 GB (13%)`

### Expected results
Disk status should be displayed correctly in the CloudMan Console

**Comment by hackdna** [comment]
It looks like the disk status is reported for the root partition instead of `/mnt/galaxy`:
```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G   12K  1.9G   1% /dev
tmpfs           377M  1.5M  375M   1% /run
/dev/xvda1       20G  5.7G   13G  31% /
none            4.0K     0  4.0K   0% /sys/fs/cgroup
none            5.0M     0  5.0M   0% /run/lock
none            1.9G     0  1.9G   0% /run/shm
none            100M     0  100M   0% /run/user
cm_processes    1.9G     0  1.9G   0% /run/cloudera-scm-agent/process
/dev/xvdf       200G   30G  171G  15% /mnt/galaxy
/dev/xvdg        80G   64G   17G  80% /mnt/galaxyIndices
```

**Comment by afgane** [comment]
Thanks for reporting this. It should be fixed now. For the time being, the code is available in `cloudman-test` bucket.
