### ISSUE TITLE
REST API Status

### ISSUE THREAD

**Issue by qspencer** [galaxyproject/cloudman#52]
Sorry to post this question here, but can someone please tell me what the status is of a REST API for Cloudman? If one exists, where is the documentation located?

**Comment by afgane** [comment]
There's an API available via BioBlend. The docs are available here: http://bioblend.readthedocs.io/en/latest/api_docs/cloudman/all.html

Let us know if you have more questions about this.

**Comment by afgane** [comment]
I'm going to close this but feel free to reopen if you have more specific questions.
