### ISSUE TITLE
Which clouds are supported?

### ISSUE THREAD

**Issue by zfrenchee** [galaxyproject/cloudman#57]
The description of this repo is "Easily create and manage compute clusters on any Cloud." I was wondering whether either GCE or MS Azure are supported, and if not, what steps would need to be taken to support them.

**Comment by zfrenchee** [comment]
@afgane @dannon @natefoo

**Comment by dannon** [comment]
@zfrenchee Right now there is no support for GCE or Azure.  Check out the https://github.com/gvlproject/cloudbridge/ project for more details -- I think that's the future for which clouds we'll be able to work with.
