### ISSUE TITLE
Enable autoscaling based on memory specification

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#68]
Submitting jobs specifying more memory than available on existing nodes results in failure.

### Steps to reproduce ###
1. Create a cluster with a `c4.large` master
1. Configure autoscaling (min nodes: 0, max nodes: 1, custom type: `c4.4xlarge`)
1. Configure a high memory job destination and use it for a tool definition. For example:
```xml
<destination id="slurm_high_memory" runner="slurm">
    <param id="nativeSpecification">--mem=25000</param>
</destination>

<tool id="wig_to_bigWig" destination="slurm_high_memory"/>
```
4. Run the tool

### Observed results ###
Galaxy log:
```
galaxy.jobs.runners.drmaa DEBUG 2017-01-27 21:00:42,163 (29) native specification is: --mem=25000
galaxy.jobs.runners.drmaa WARNING 2017-01-27 21:00:42,167 (29) drmaa.Session.runJob() failed, will retry: code 1: slurm_submit_batch_job: Requested node configuration is not available
...
galaxy.jobs.runners.drmaa ERROR 2017-01-27 21:01:07,190 (29) All attempts to submit job failed
```

### Expected results ###
Job submission should succeed and autoscaling should add an instance of the specified type.

**Comment by nuwang** [comment]
Closing because old version
