### ISSUE TITLE
Support for the new AWS Ohio region us-east-2

### ISSUE THREAD

**Issue by hackdna** [galaxyproject/cloudman#69]
Virginia region us-east-1 is the oldest AWS region. It appears to have the highest service error rates of all regions ([example](https://gigaom.com/2015/01/22/aws-boosted-cloud-reliability-in-2014-new-stats-show/)).

The new us-east-2 region has the same pricing and geographic proximity to the US northeast while providing [better performance](https://www.concurrencylabs.com/blog/choose-your-aws-region-wisely/) and potentially better capacity.

[Now Open – AWS US East (Ohio) Region](https://aws.amazon.com/blogs/aws/now-open-aws-us-east-ohio-region/)

**Comment by afgane** [comment]
I added it to the new launcher: https://beta.launch.usegalaxy.org/marketplace/appliance/galaxy-cloud

I'll close this issue as things seem to work fine there but please reopen it if you encounter issues or have other comments.

**Comment by hackdna** [comment]
`us-east-2` is only available for 16.10 on https://beta.launch.usegalaxy.org/catalog/appliance/galaxy-cloud
Would it be possible to make it available for all the releases?

**Comment by afgane** [comment]
I've added it for releases 16.07 and 16.10. The only other available release at this point is 16.04 but that one is not compatible with the available image in that region so unless you really need it, I've haven't done that one.

**Comment by hackdna** [comment]
Thanks, I'm testing 17.05 now so this should be sufficient if we are able to upgrade.
