### ISSUE TITLE
Update Galaxy to 18.05

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#79]
Do a (GVL) release with CloudMan 1 to include Galaxy 18.05:
- [x] Build a new updated machine image
- [x] Update CloudMan code to work with uwsgi
- [x] Allow manual editing of Galaxy config and not have CloudMan overwrite it
- [x] Base all tool installs on Conda; however, most likely won't install the dependencies due to size and instead install only the wrappers with the deps being filled in on first job run (potentially install a few common deps)
- [ ] Build and upload the file system archive; create CloudFront distribution; update refs
- [ ] 10 other things I'm forgetting or will emerge

**Comment by nuwang** [comment]
Closing because old version.
