### ISSUE TITLE
Does cloudman want a new logo?

### ISSUE THREAD

**Issue by martenson** [galaxyproject/cloudman#8]
@petrkadlec has a few ideas:
![cloudman](https://cloud.githubusercontent.com/assets/1814954/7454261/e60be6aa-f23f-11e4-947d-14ae13552694.png)

**Comment by jxtx** [comment]
Cloudman's cloudman is probably the best logo we've ever had for any Galaxy project. Any attempt at a new logo should preserve him.

**Comment by dannon** [comment]
Agreed with @jxtx, love cloudman's cloudman.

**Comment by petrkadlec** [comment]
Some ideas with the cloudman's cloudman, just changed typography and colors to conform to the new galaxy logo.
![cloudman2](https://cloud.githubusercontent.com/assets/12165223/7525754/6a5f3f96-f50c-11e4-8bb7-94b1bd5891cd.png)

**Comment by afgane** [comment]
My favorite is the top-most picture here.

**Comment by nitesh1989** [comment]
I agree with @afgane. @petrkadlec 's comment and top-most picture.

**Comment by dannon** [comment]
I definitely like the first one best of the bunch here, but the vertical
balance looks off (something #2 and #3 attempt to address).  Anyone have
ideas for tweaking that?

**Comment by nitesh1989** [comment]
Justify the height i guess? Take #2 and make the "cloud" bolder?

**Comment by petrkadlec** [comment]
You feel pretty confident about the cloudman giving him a pair of sunglasses.. :) New designs based on your comments...
![cloudman3](https://cloud.githubusercontent.com/assets/12165223/7528029/d405a8de-f522-11e4-93de-59e80863d15a.png)

**Comment by nitesh1989** [comment]
Very much into design #1 and #2. But i'll let @afgane and @dannon .

**Comment by jxtx** [comment]
I like #4. Not so into the sunglasses, he looks less like a cloud with them
:)

On Thursday, May 7, 2015, Petr Kadlec <notifications@github.com> wrote:

> You feel pretty confident about the cloudman giving him a pair of
> sunglasses.. :) New designs based on your comments...
> [image: cloudman3]
> <https://cloud.githubusercontent.com/assets/12165223/7528029/d405a8de-f522-11e4-93de-59e80863d15a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/cloudman/issues/8#issuecomment-100047376>
> .
>


-- 
jt (mobile)

**Comment by martenson** [comment]
ping @afgane - do you want to continue with this or have you decided?

**Comment by afgane** [comment]
To keep signage in sync with the rest of the project, we should adopt one of these. I'd stick with the logo closest to the current one, namely #3 above then. In addition, for horizontally-constrained spaces, it'd be good to have a more compact version; I've used logo below in the past so would be good to have that as well.
![cloudman_logo_black_squared](https://cloud.githubusercontent.com/assets/338642/9853005/7117dba8-5acf-11e5-8c91-16ed96e3ba1a.png)

**Comment by martenson** [comment]
Done. All the resources/formats for the new logo is available at https://drive.google.com/drive/folders/0BycJJtbagAMTeVI2UzktTnB0VFU (login required)
