### ISSUE TITLE
Please add "Unique" tools to CloudMan instances

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/cloudman#83]
I'm running an instance on AWS (launched from CloudLaunch):

```
Appliance: Genomics Virtual Lab (GVL) 
Version: GVL 4.4.0 RC1 (Galaxy 18.05)
Cloud: amazon-us-east-n-virginia 
```
Neither the "Unique" or "Unique Lines" tools are on the instance.

I think these are useful enough to include.  However, if this omission was conscious then you can ignore it.

**Comment by afgane** [comment]
Is it these two tools?
- https://toolshed.g2.bx.psu.edu/view/xuebing/unique_line/a43de04b5a62
- https://toolshed.g2.bx.psu.edu/view/bgruening/unique/7ce75adb93be

**Comment by tnabtaf** [comment]
Björn's is the one that's in use on Main.  So, that would be good.

The other one (lines) is in this repo: https://toolshed.g2.bx.psu.edu/repository?repository_id=2593fd36ae8011aa

Which is big, but is kinda useful.

**Comment by afgane** [comment]
The tools were installed and a new version of the file system uploaded so should be good to go.

**Comment by tnabtaf** [comment]
Thanks.
