### ISSUE TITLE
Unclear where to report an error on a GVL instance.

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/cloudman#84]
I'm running a GVL instance on AWS, launched from CloudLaunch:

```
Appliance: Genomics Virtual Lab (GVL) 
Version: GVL 4.4.0 RC1 (Galaxy 18.05)
Cloud: amazon-us-east-n-virginia 
```

And I got the error reported in issue #82.  It wasn't at all clear what I should do to report the error. Clicking on the Help pulldown has an item called Support. That leads to https://www.gvl.org.au/help/ and from there I could not find anything about how to report bugs.

**Comment by nuwang** [comment]
@tnabtaf Do you have any opinions on how the help link could be improved? Currently, the normal procedure is to just email, which will result in an issue being registered with the ticketing system. We could perhaps also point to github as a place to register issues, or make it more explicit that emailing will result in a tracked ticket.

**Comment by tnabtaf** [comment]
@nuwang I'm good with an email.  I just couldn't find anything like a "Report a bug / request support by email" link on the support page.  Either

1. Make that link more prominent (or add it)
2. Or conclude that it's already prominent and that I should have seen it.  :-)

**Comment by nuwang** [comment]
Closing because v1 cloudman is no longer maintained and will receive bug fixes only.
