### ISSUE TITLE
Install Tools not showing results in Admin view and/or is astonishingly slow.

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/cloudman#85]
I'm running a GVL instance on AWS, launched with CloudLaunch:

```
Appliance: Genomics Virtual Lab (GVL) 
Version: GVL 4.4.0 RC1 (Galaxy 18.05)
Cloud: amazon-us-east-n-virginia 
```

I can't get either the "Install new tools" or "Install new tools (Beta) to work, or they are mind-numbingly slow.

If the mind-numbingly slow is due to something on the toolshed end, then, um, close this request.

**Comment by afgane** [comment]
Can you try with the latest update (i.e., RC2)? My attempts have worked fine.

**Comment by tnabtaf** [comment]
Will do, on Monday.

**Comment by nuwang** [comment]
Closing because old version of Galaxy.
