### ISSUE TITLE
Unable to install tools from Tool Shed

### ISSUE THREAD

**Issue by tnabtaf** [galaxyproject/cloudman#86]
I am able to request that a tool be installed on my local instance, but the tool does not finish installing.

In the Admin -> Tool Management -> Manage Tools window, the requested tool hangs at the "Cloning" step and displays a question mark icon in the 2nd column for the tool. Hovering over that shows:

"Unable to get information from the Tool Shed"

**Comment by afgane** [comment]
Any specific tool? I tried a few random tools and they're all installing now. Could be the latest update or a Toolshed... If you could try again and let us know, we'll poke at it more.

**Comment by tnabtaf** [comment]
The tools I tried were Björn's text processing repo, and ... I can't remember.

If we can leave this open through next week, I will investigate further.  May have been an intermittent toolshed problem...

**Comment by nuwang** [comment]
Closing because obsolete version.
