### ISSUE TITLE
Custom Galaxy conf templates are not preserved across system shutdowns.

### ISSUE THREAD

**Issue by afgane** [galaxyproject/cloudman#87]
> In general it seems to be working well however I have experienced issues with retaining job_conf over cluster invocations, for example if I place a new jobconf in /opt/cloudman/config/conftemplates/ and restart galaxy in cloudman the new job_conf is loaded correctly. 

> However, if I terminate the cluster and then retrieve it with cloudlaunch the   /opt/cloudman/config/conftemplates/ folder is deleted and she default jobconf is loaded , which seems unusual because all my other changes have persisted?

**Comment by nuwang** [comment]
conftemplates do not persist over cluster terminations because they are not stored in s3. No longer maintained so won't be fixed.
