### ISSUE TITLE
Adding additional worker nodes causes job failure, collections don't error out

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/cloudman#88]
When jobs/collections are running and additional worker nodes are added to the Cloudman instance, some of the jobs/collections stop running and return empty jobs/collections in the that are green state. Not all collections exhibit this behavior, some collections are stopped and in the error state. 

The two issues: 
- Adding workers interrupts ongoing jobs
- Interrupted jobs are not always marked in the error state, collections contain empty data items

Behavior observed using the GVL 4.4.0 RC2 (Galaxy 18.05)

**Comment by MoHeydarian** [comment]
Update: removing idle worker nodes while jobs are running leads to the same issue above.

**Comment by almahmoud** [comment]
Should be fixed with the new CloudMan: https://github.com/galaxyproject/cloudman/pull/90
