### ISSUE TITLE
Jobs aren't evenly distributed across workers. 

### ISSUE THREAD

**Issue by MoHeydarian** [galaxyproject/cloudman#89]
When starting a workflow or a handful of jobs, they initially run evenly across available worker nodes, but over time all of the jobs end up running on only one worker.  

Trying to add additional nodes while jobs are ongoing or queued results in https://github.com/galaxyproject/cloudman/issues/88

Behavior observed using the GVL 4.4.0 RC2 (Galaxy 18.05)

**Comment by nuwang** [comment]
Closing because v1 cloudman is no longer maintained and will receive bug fixes only.
